POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RAcm9vdC5jb20iLCJpZCI6MSwiaWF0IjoxNzMyNTMxMTQwfQ.sWzyxuGLykBw9QqvT15uaPQXcfJtgJH33SFFGk9EDNs

{
  "title": "Test",
  "author": "Test Author",
  "url": "www.fullstackopen.com",
  "likes": 8,
  "year": 2023
}