
PUT http://localhost:3003/api/readinglists/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RAcm9vdC5jb20iLCJpZCI6MSwiaWF0IjoxNzMyNTM4NTUxfQ.DUoeOhRmFwgQyTrFE3BcfirckFjdBxm_rjBrykchA60

{ 
    "read": true
}